- name: git clone dotfile
  git:
    repo: https://github.com/takuminish/.dotfiles
    dest: /home/.dotfiles
- name: zsh symlink
  file:
    src: /home/.dotfiles/zsh/{{ item }}
    dest: /home/vagrant/{{ item }}
    state: link
    force: yes
  with_items:
    - .zsh.d
    - .zshrc