 - name: init install
   apt:
     name:
       - zsh
       - git
       - gcc
       - autoconf
       - bison
       - build-essential
       - libssl-dev
       - libyaml-dev
       - libreadline6-dev
       - zlib1g-dev
       - libncurses5-dev
       - libffi-dev
       - libgdbm5
       - libgdbm-dev
     update_cache: yes
     force_apt_get: yes

  